/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "s3ePushWoosh.h"


// Define S3E_EXT_SKIP_LOADER_CALL_LOCK on the user-side to skip LoaderCallStart/LoaderCallDone()-entry.
// e.g. in s3eNUI this is used for generic user-side IwUI-based implementation.
#ifndef S3E_EXT_SKIP_LOADER_CALL_LOCK
#if (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP)) || defined I3D_ARCH_NACLX86_64
// For platforms missing stack-switching (WP8, NaCl, etc.) make loader-entry via LoaderCallStart/LoaderCallDone() on the user-side.
#define LOADER_CALL_LOCK
#endif
#endif


#include "s3ePushWoosh_interface.h"

static s3ePushWooshFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xffcac5e0, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: s3ePushWoosh");

        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xffcac5e0, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3ePushWooshAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult s3ePushWooshRegister(s3ePushWooshCallback cbid, s3eCallback fn, void* userData)
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[0] func: s3ePushWooshRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshRegister);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshRegister(cbid, fn, userData);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshRegister);
#endif

    return ret;
}

s3eResult s3ePushWooshUnRegister(s3ePushWooshCallback cbid, s3eCallback fn)
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[1] func: s3ePushWooshUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshUnRegister);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshUnRegister(cbid, fn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshUnRegister);
#endif

    return ret;
}

s3eBool s3ePushWooshNotificationsAvailable()
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[2] func: s3ePushWooshNotificationsAvailable"));

    if (!_extLoad())
        return S3E_FALSE;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationsAvailable);
#endif

    s3eBool ret = g_Ext.m_s3ePushWooshNotificationsAvailable();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationsAvailable);
#endif

    return ret;
}

s3eResult s3ePushWooshNotificationRegister()
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[3] func: s3ePushWooshNotificationRegister"));

    if (!_extLoad())
        return S3E_RESULT_SUCCESS;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationRegister);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshNotificationRegister();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationRegister);
#endif

    return ret;
}

s3eResult s3ePushWooshNotificationRegisterWithPWAppID(const char * pushwooshAppId)
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[4] func: s3ePushWooshNotificationRegisterWithPWAppID"));

    if (!_extLoad())
        return S3E_RESULT_SUCCESS;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationRegisterWithPWAppID);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshNotificationRegisterWithPWAppID(pushwooshAppId);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationRegisterWithPWAppID);
#endif

    return ret;
}

char * s3ePushWooshGetToken()
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[5] func: s3ePushWooshGetToken"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshGetToken);
#endif

    char * ret = g_Ext.m_s3ePushWooshGetToken();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshGetToken);
#endif

    return ret;
}

s3eResult s3ePushWooshNotificationUnRegister()
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[6] func: s3ePushWooshNotificationUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_SUCCESS;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationUnRegister);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshNotificationUnRegister();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationUnRegister);
#endif

    return ret;
}

s3eResult s3ePushWooshNotificationSetIntTag(const char * tagName, int tagValue)
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[7] func: s3ePushWooshNotificationSetIntTag"));

    if (!_extLoad())
        return S3E_RESULT_SUCCESS;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationSetIntTag);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshNotificationSetIntTag(tagName, tagValue);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationSetIntTag);
#endif

    return ret;
}

s3eResult s3ePushWooshNotificationSetStringTag(const char * tagName, const char * tagValue)
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[8] func: s3ePushWooshNotificationSetStringTag"));

    if (!_extLoad())
        return S3E_RESULT_SUCCESS;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationSetStringTag);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshNotificationSetStringTag(tagName, tagValue);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationSetStringTag);
#endif

    return ret;
}

s3eResult s3ePushWooshNotificationSetBadgeNumber(int badgeValue)
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[9] func: s3ePushWooshNotificationSetBadgeNumber"));

    if (!_extLoad())
        return S3E_RESULT_SUCCESS;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationSetBadgeNumber);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshNotificationSetBadgeNumber(badgeValue);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshNotificationSetBadgeNumber);
#endif

    return ret;
}

s3eResult s3ePushWooshClearLocalNotifications()
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[10] func: s3ePushWooshClearLocalNotifications"));

    if (!_extLoad())
        return S3E_RESULT_SUCCESS;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshClearLocalNotifications);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshClearLocalNotifications();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshClearLocalNotifications);
#endif

    return ret;
}

s3eResult s3ePushWooshStartLocationTracking()
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[11] func: s3ePushWooshStartLocationTracking"));

    if (!_extLoad())
        return S3E_RESULT_SUCCESS;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshStartLocationTracking);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshStartLocationTracking();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshStartLocationTracking);
#endif

    return ret;
}

s3eResult s3ePushWooshStopLocationTracking()
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[12] func: s3ePushWooshStopLocationTracking"));

    if (!_extLoad())
        return S3E_RESULT_SUCCESS;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshStopLocationTracking);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshStopLocationTracking();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshStopLocationTracking);
#endif

    return ret;
}

s3eResult s3ePushWooshScheduleLocalNotification(const char * message, int seconds, const char * userdata)
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[13] func: s3ePushWooshScheduleLocalNotification"));

    if (!_extLoad())
        return S3E_RESULT_SUCCESS;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshScheduleLocalNotification);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshScheduleLocalNotification(message, seconds, userdata);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshScheduleLocalNotification);
#endif

    return ret;
}

s3eResult s3ePushWooshSetAndroidNotificationMultiMode(bool enable)
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[14] func: s3ePushWooshSetAndroidNotificationMultiMode"));

    if (!_extLoad())
        return S3E_RESULT_SUCCESS;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshSetAndroidNotificationMultiMode);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshSetAndroidNotificationMultiMode(enable);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshSetAndroidNotificationMultiMode);
#endif

    return ret;
}

s3eResult s3ePushWooshSetUserId(const char * userId)
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[15] func: s3ePushWooshSetUserId"));

    if (!_extLoad())
        return S3E_RESULT_SUCCESS;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshSetUserId);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshSetUserId(userId);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshSetUserId);
#endif

    return ret;
}

s3eResult s3ePushWooshPostEvent(const char * event, const char * attributes)
{
    IwTrace(PUSHWOOSH_VERBOSE, ("calling s3ePushWoosh[16] func: s3ePushWooshPostEvent"));

    if (!_extLoad())
        return S3E_RESULT_SUCCESS;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshPostEvent);
#endif

    s3eResult ret = g_Ext.m_s3ePushWooshPostEvent(event, attributes);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3ePushWooshPostEvent);
#endif

    return ret;
}
